added `CLI` and refactoring to latest BASH version

diff --git a/equilibrium-core b/equilibrium-core
--- a/equilibrium-core
+++ b/equilibrium-core
@@ -1,63 +1,50 @@
 #!/usr/bin/env bash
 #
-# @@script: equilibrium_engine
-# @@description: Equilibrium Core
-# @@author: Loouis Low
-# @@copyright: Loouis Low (https://loouislow81.github.io)
-# @@license: MIT License
+# @@script: equilibrium-core.sh
+# @@description: equilibrium core program script
+# @@author: Loouis Low (loouis@gmail.com)
+# @@copyright: Loouis Low (https://github.com/loouislow81/equilibrium)
+# @@license: MIT
 #
 
+# get script name
 binary=$(basename $0 | sed "s/\.sh$//")
+APPNAME="$binary"
 
-###### vars ######
+###### imports ######
 
-# ansi
-blue='\e[94m'
-cyan='\e[36m'
-green='\e[92m'
-red='\e[91m'
-dgray='\e[90m'
-lgray='\e[37m'
-bggray='\e[100m'
-bgcyan='\e[46m'
-nc='\033[0m'
-bold=$(tput bold)
-normal=$(tput sgr0)
-tag='\e[100m'
-title="${blue}(equilibrium)${nc}"
-arrow="${red}>>${nc}"
-bandwidth_limit=30000
+source /etc/equilibrium.conf
 
-# -----------------------------------------------------------------------------
-# Check if Rsync installed
-# -----------------------------------------------------------------------------
+###### funcs ######
 
+# check if `rsync` installed
 if ! [ -x "$(command -v rsync)" ]; then
-  echo;echo '$title installing rsync...' >&2;echo
-  sudo apt install -y rsync;echo
+  echo -e "$title installing $arrow rsync" >&2
+  sudo apt install -y -qq rsync
 fi
 
-APPNAME="${blue}($binary)${nc}"
+# logging
+fn_log_info() {
+  echo -e "$APPNAME $1"
+}
 
-# -----------------------------------------------------------------------------
-# Log functions
-# -----------------------------------------------------------------------------
+fn_log_warn() {
+  echo -e "$APPNAME ${red}(WARNING)${nc} $1" 1>&2
+}
 
-fn_log_info()  { echo -e "$APPNAME $1"; }
-fn_log_warn()  { echo -e "$APPNAME ${red}(WARNING)${nc} $1" 1>&2; }
-fn_log_error() { echo -e "$APPNAME ${red}([ERROR)${nc} $1" 1>&2; }
-fn_log_info_cmd()  {
+fn_log_error() {
+  echo -e "$APPNAME ${red}([ERROR)${nc} $1" 1>&2
+}
+
+fn_log_info_cmd() {
   if [ -n "$SSH_CMD" ]; then
-    echo -e "$APPNAME $SSH_CMD '$1'";
+    echo -e "$APPNAME $SSH_CMD '$1'"
   else
-    echo -e "$APPNAME $1";
+    echo -e "$APPNAME $1"
   fi
 }
 
-# -----------------------------------------------------------------------------
-# Make sure everything really stops when CTRL+C is pressed
-# -----------------------------------------------------------------------------
-
+# make sure everything really stops when CTRL+C is pressed
 fn_terminate_script() {
   fn_log_info "SIGINT caught."
   exit 1
@@ -65,13 +52,9 @@ fn_terminate_script() {
 
 trap 'fn_terminate_script' SIGINT
 
-# -----------------------------------------------------------------------------
-# Small utility functions for reducing code duplication
-# -----------------------------------------------------------------------------
+# small utility functions for reducing code duplication
 fn_display_usage() {
-
   clear
-
   echo;echo "#### equilibrium #####################################################";echo
   echo "Usage: $(basename $0) [OPTION]... <SOURCE> <[USER@HOST:]DESTINATION> [exclude-pattern-file]";echo
   echo "Options"
@@ -82,7 +65,7 @@ fn_display_usage() {
 }
 
 fn_parse_date() {
-  # Converts YYYY-MM-DD-HHMMSS to YYYY-MM-DD HH:MM:SS and then to Unix Epoch.
+  # converts YYYY-MM-DD-HHMMSS to YYYY-MM-DD HH:MM:SS and then to Unix epoch.
   case "$OSTYPE" in
     linux*) date -d "${1:0:10} ${1:11:2}:${1:13:2}:${1:15:2}" +%s ;;
     cygwin*) date -d "${1:0:10} ${1:11:2}:${1:13:2}:${1:15:2}" +%s ;;
@@ -96,7 +79,7 @@ fn_find_backups() {
 }
 
 fn_expire_backup() {
-  # Double-check that we're on a backup destination to be completely
+  # double-check that we're on a backup destination to be completely
   # sure we're deleting the right folder
   if [ -z "$(fn_find_backup_marker "$(dirname -- "$1")")" ]; then
     fn_log_error "$1 is not on a backup destination - aborting."
@@ -108,8 +91,7 @@ fn_expire_backup() {
 }
 
 fn_parse_ssh() {
-  if [[ "$DEST_FOLDER" =~ ^[A-Za-z0-9\._%\+\-]+@[A-Za-z0-9.\-]+\:.+$ ]]
-  then
+  if [[ "$DEST_FOLDER" =~ ^[A-Za-z0-9\._%\+\-]+@[A-Za-z0-9.\-]+\:.+$ ]]; then
     SSH_USER=$(echo "$DEST_FOLDER" | sed -E  's/^([A-Za-z0-9\._%\+\-]+)@([A-Za-z0-9.\-]+)\:(.+)$/\1/')
     SSH_HOST=$(echo "$DEST_FOLDER" | sed -E  's/^([A-Za-z0-9\._%\+\-]+)@([A-Za-z0-9.\-]+)\:(.+)$/\2/')
     SSH_DEST_FOLDER=$(echo "$DEST_FOLDER" | sed -E  's/^([A-Za-z0-9\._%\+\-]+)@([A-Za-z0-9.\-]+)\:(.+)$/\3/')
@@ -119,8 +101,7 @@ fn_parse_ssh() {
 }
 
 fn_run_cmd() {
-  if [ -n "$SSH_CMD" ]
-  then
+  if [ -n "$SSH_CMD" ]; then
     eval "$SSH_CMD '$1'"
   else
     eval $1
@@ -151,10 +132,7 @@ fn_ln() {
   fn_run_cmd "ln -s -- '$1' '$2'"
 }
 
-# -----------------------------------------------------------------------------
-# Source and destination information
-# -----------------------------------------------------------------------------
-
+# source and destination information
 SSH_USER=""
 SSH_HOST=""
 SSH_DEST_FOLDER=""
@@ -166,47 +144,47 @@ SRC_FOLDER=""
 DEST_FOLDER=""
 EXCLUSION_FILE=""
 
-RSYNC_FLAGS="-D --compress --partial --bwlimit=${bandwidth_limit} --numeric-ids --links --hard-links --one-file-system --itemize-changes --times --recursive --perms --owner --group"
+RSYNC_FLAGS="-D --partial --progress --compress --numeric-ids --links --hard-links --one-file-system --itemize-changes --times --recursive --perms --owner --group --bwlimit=${bandwidth_limit} --exclude-from=${exclusion_list}"
 
 while :; do
   case $1 in
 
     -h|-\?|--help)
-    fn_display_usage
+      fn_display_usage
     exit;;
 
     -p|--port)
     shift
-    SSH_PORT=$1
+      SSH_PORT=$1
     ;;
 
     --rsync-get-flags)
     shift
-    echo $RSYNC_FLAGS
+      echo $RSYNC_FLAGS
     exit;;
 
     --rsync-set-flags)
     shift
-    RSYNC_FLAGS="$1"
+      RSYNC_FLAGS="$1"
     ;;
 
     --)
     shift
-    SRC_FOLDER="$1"
-    DEST_FOLDER="$2"
-    EXCLUSION_FILE="$3"
+      SRC_FOLDER="$1"
+      DEST_FOLDER="$2"
+      EXCLUSION_FILE="$3"
     break;;
 
     -?*)
-    fn_log_error "Unknown option: \"$1\""
-    fn_log_info ""
-    fn_display_usage
+      fn_log_error "Unknown option: \"$1\""
+      fn_log_info ""
+      fn_display_usage
     exit 1;;
 
     *)
-    SRC_FOLDER="$1"
-    DEST_FOLDER="$2"
-    EXCLUSION_FILE="$3"
+      SRC_FOLDER="$1"
+      DEST_FOLDER="$2"
+      EXCLUSION_FILE="$3"
     break
 
   esac
@@ -214,18 +192,19 @@ while :; do
   shift
 done
 
-# Display usage information if required arguments are not passed
+# display usage information if required arguments are not passed
 if [[ -z "$SRC_FOLDER" || -z "$DEST_FOLDER" ]]; then
   fn_display_usage
   exit 1
 fi
 
-# Strips off last slash. Note that it means the root folder "/"
+# strips off last slash. Note that it means the root folder "/"
 # will be represented as an empty string "", which is fine
 # with the current script (since a "/" is added when needed)
 # but still something to keep in mind.
 # Don't think it would with DEST_FOLDER set to "/" though,
 # but there's probably not a use case for this anyway.
+
 SRC_FOLDER="${SRC_FOLDER%/}"
 DEST_FOLDER="${DEST_FOLDER%/}"
 
@@ -242,14 +221,16 @@ for ARG in "$SRC_FOLDER" "$DEST_FOLDER" "$EXCLUSION_FILE"; do
   fi
 done
 
-# -----------------------------------------------------------------------------
-# Check that the destination drive is a backup drive
-# -----------------------------------------------------------------------------
-
+# check that the destination drive is a backup drive
 # TODO: check that the destination supports hard links
 
-fn_backup_marker_path() { echo "$1/backup.marker"; }
-fn_find_backup_marker() { fn_find "$(fn_backup_marker_path "$1")" 2> /dev/null; }
+fn_backup_marker_path() {
+  echo "$1/backup.marker"
+}
+
+fn_find_backup_marker() {
+  fn_find "$(fn_backup_marker_path "$1")" 2> /dev/null
+}
 
 if [ -z "$(fn_find_backup_marker "$DEST_FOLDER")" ]; then
   fn_log_info "Safety check failed - the destination does not appear to be a backup folder or drive (marker file not found)."
@@ -260,36 +241,28 @@ if [ -z "$(fn_find_backup_marker "$DEST_FOLDER")" ]; then
   exit 1
 fi
 
-# -----------------------------------------------------------------------------
-# Setup additional variables
-# -----------------------------------------------------------------------------
+# setup additional variables
 
-# Date logic
+# date logic
 NOW=$(date +"%Y-%m-%d-%H%M%S")
 EPOCH=$(date "+%s")
-KEEP_ALL_DATE=$((EPOCH - 86400))       # 1 day ago
+KEEP_ALL_DATE=$((EPOCH - 86400)) # 1 day ago
 KEEP_DAILIES_DATE=$((EPOCH - 2678400)) # 31 days ago
 
-export IFS=$'\n' # Better for handling spaces in filenames.
+export IFS=$'\n' # better for handling spaces in filenames.
 PROFILE_FOLDER="$HOME/.$APPNAME"
 DEST="$DEST_FOLDER/$NOW"
 PREVIOUS_DEST="$(fn_find_backups | head -n 1)"
 INPROGRESS_FILE="$DEST_FOLDER/backup.inprogress"
 MYPID="$$"
 
-# -----------------------------------------------------------------------------
-# Create profile folder if it doesn't exist
-# -----------------------------------------------------------------------------
-
+# create profile folder if it doesn't exist
 if [ ! -d "$PROFILE_FOLDER" ]; then
   fn_log_info "Creating profile folder in '$PROFILE_FOLDER'..."
   mkdir -- "$PROFILE_FOLDER"
 fi
 
-# -----------------------------------------------------------------------------
-# Handle case where a previous backup failed or was interrupted.
-# -----------------------------------------------------------------------------
-
+# handle case where a previous backup failed or was interrupted.
 if [ -n "$(fn_find "$INPROGRESS_FILE")" ]; then
   if [ "$OSTYPE" == "cygwin" ]; then
     # TODO: Cygwin reports the name of currently running Bash scripts as just "/usr/bin/bash"
@@ -319,18 +292,18 @@ if [ -n "$(fn_find "$INPROGRESS_FILE")" ]; then
   fi
 fi
 
-# Run in a loop to handle the "No space left on device" logic.
+# run in a loop to handle the "No space left on device" logic.
 while : ; do
 
   # -----------------------------------------------------------------------------
-  # Check if we are doing an incremental backup (if previous backup exists).
+  # check if we are doing an incremental backup (if previous backup exists).
   # -----------------------------------------------------------------------------
 
   LINK_DEST_OPTION=""
   if [ -z "$PREVIOUS_DEST" ]; then
     fn_log_info "No previous backup - creating new one."
   else
-    # If the path is relative, it needs to be relative to the destination. To keep
+    # if the path is relative, it needs to be relative to the destination. To keep
     # it simple, just use an absolute path.
     PREVIOUS_DEST="$(fn_get_absolute_path "$PREVIOUS_DEST")"
     fn_log_info "Previous backup found - doing incremental backup from $SSH_FOLDER_PREFIX$PREVIOUS_DEST"
@@ -338,7 +311,7 @@ while : ; do
   fi
 
   # -----------------------------------------------------------------------------
-  # Create destination folder if it doesn't already exists
+  # create destination folder if it doesn't already exists
   # -----------------------------------------------------------------------------
 
   if [ -z "$(fn_find "$DEST -type d" 2> /dev/null)" ]; then
@@ -347,16 +320,17 @@ while : ; do
   fi
 
   # -----------------------------------------------------------------------------
-  # Purge certain old backups before beginning new backup.
+  # purge certain old backups before beginning new backup.
   # -----------------------------------------------------------------------------
 
-  # Default value for $PREV ensures that the most recent backup is never deleted.
+  # default value for $PREV ensures that the most recent backup is never deleted.
   PREV="0000-00-00-000000"
+
   for FILENAME in $(fn_find_backups | sort -r); do
     BACKUP_DATE=$(basename "$FILENAME")
     TIMESTAMP=$(fn_parse_date $BACKUP_DATE)
 
-    # Skip if failed to parse date...
+    # skip if failed to parse date...
     if [ -z "$TIMESTAMP" ]; then
       fn_log_warn "Could not parse date: $FILENAME"
       continue
@@ -376,7 +350,7 @@ while : ; do
   done
 
   # -----------------------------------------------------------------------------
-  # Start backup
+  # start backup
   # -----------------------------------------------------------------------------
 
   LOG_FILE="$PROFILE_FOLDER/$(date +"%Y-%m-%d-%H%M%S").log"
@@ -386,15 +360,19 @@ while : ; do
   fn_log_info "To:   $SSH_FOLDER_PREFIX$DEST/"
 
   CMD="rsync"
+
   if [ -n "$SSH_CMD" ]; then
     CMD="$CMD  -e 'ssh -p $SSH_PORT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
   fi
+
   CMD="$CMD $RSYNC_FLAGS"
   CMD="$CMD --log-file '$LOG_FILE'"
+
   if [ -n "$EXCLUSION_FILE" ]; then
-    # We've already checked that $EXCLUSION_FILE doesn't contain a single quote
+    # we've already checked that $EXCLUSION_FILE doesn't contain a single quote
     CMD="$CMD --exclude-from '$EXCLUSION_FILE'"
   fi
+
   CMD="$CMD $LINK_DEST_OPTION"
   CMD="$CMD -- '$SRC_FOLDER/' '$SSH_FOLDER_PREFIX$DEST/'"
   CMD="$CMD | grep -E '^deleting|[^/]$'"
@@ -407,7 +385,7 @@ while : ; do
   eval $CMD
 
   # -----------------------------------------------------------------------------
-  # Check if we ran out of space
+  # check if we ran out of space
   # -----------------------------------------------------------------------------
 
   # TODO: find better way to check for out of space condition without parsing log.
@@ -423,23 +401,25 @@ while : ; do
 
     fn_expire_backup "$(fn_find_backups | tail -n 1)"
 
-    # Resume backup
+    # resume backup
     continue
   fi
 
   # -----------------------------------------------------------------------------
-  # Check whether rsync reported any errors
+  # check whether rsync reported any errors
   # -----------------------------------------------------------------------------
+
   if [ -n "$(grep "rsync:" "$LOG_FILE")" ]; then
     fn_log_warn "Rsync reported a warning, please check '$LOG_FILE' for more details."
   fi
+
   if [ -n "$(grep "rsync error:" "$LOG_FILE")" ]; then
     fn_log_error "Rsync reported an error, please check '$LOG_FILE' for more details."
     exit 1
   fi
 
   # -----------------------------------------------------------------------------
-  # Add symlink to last successful backup
+  # add symlink to last successful backup
   # -----------------------------------------------------------------------------
 
   fn_rm "$DEST_FOLDER/latest"
@@ -448,7 +428,7 @@ while : ; do
   fn_rm "$INPROGRESS_FILE"
   rm -f -- "$LOG_FILE"
 
-  fn_log_info "Backup completed without errors."
+  fn_log_info "(!!) Backup completed without errors."
 
   exit 0
 done
